language: "node_js"
node_js:
  - "5"
  - "4"
  - "3"
  - "2"
  - "1"
  - "0.12"

before_install:
  - "npm install coveralls"

script:
  - "make all"

after_success:
  - "make coverage-report"

sudo: false
